### ISSUE TITLE
Design Components Overview page

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1213]
goal: A page that will serve to see an overview of all components in the library.

This page main use is to assist the user to find quickly the component they are looking for.

### Current
http://sap.github.io/techne/components.html

Maybe we to put them in categories...

**Comment by jeannewalters** [comment]
@joseegm Based on some review of other sites and the need to link to this overview page from the homepage, we should have this page. I would suggest we update the current Components overview page with images for each component.

Here's an example - http://carbondesignsystem.com/components/overview

Ideally, @LeoT7508 or @jinjiahuangsap can create images for each base component that will look good as a whole on this overview page.

**Comment by joseegm** [comment]
@LeoT7508 
Let me know when you have something to show

**Comment by LeoT7508** [comment]
@joseegm 

When we have something to share we will. This weeks team call will probably be a good time to share stuff Jinjia and I have worked on.

**Comment by jinjiahuangsap** [comment]
@joseegm 

Here's the newest version for the component overview page. We put a placeholder image for the toolbar since it is still in progress.
https://app.zeplin.io/project/59fc8d826e1e5e806854ddbf/screen/5a4cf9d5b407a8391fd42ec6

![fundamentalui_components template](https://user-images.githubusercontent.com/32305332/34736091-66791450-f537-11e7-8bca-e4dba608b0ff.png)

**Comment by joseegm** [comment]
@jinjiahuangsap 

I love it! Really good. Thank you very much. We can close these one :)
