### ISSUE TITLE
Action bar Title alignment

### ISSUE THREAD

**Issue by gcho1023** [SAP/techne#1269]
In previous techne, the Page title of the action bar was centered but today it is left aligned.  Had a meeting with other UX Designers across EC who have tested this before and users are getting confused that the back button is too close to the Page Title and users who are using this relates the back button to the actual Page Title than thinking "I'm going back to the previous page".  What was the reason for left aligning this Page title while other actions and subhead text are centered aligned? Is it due to the action buttons?

<img width="788" alt="screen shot 2017-11-30 at 3 32 55 pm" src="https://user-images.githubusercontent.com/32933889/33456058-cf0cd204-d5e3-11e7-9155-9e695fb688ba.png">

**Comment by jeannewalters** [comment]
@joseegm @gcho1023 - The left alignment definitely gives more space for the actions on the right. I believe the comment today around the back button and usability testing was around the arrow proximity to the page title and how that leads to confusion about where the user is and where they go when they go when clicking on that button.  

@joseegm or @saadmhybris or @LeoT7508  - will the Back button take the user back historically or hierarchically?  Since Builder is no longer a use case, we won't have the situation where the user has two options right next to each other that do different things. Below are two ways that apps listed as examples do it from the Invision screenshots:

1) This app has a vertical line separating the two things:
![image](https://user-images.githubusercontent.com/24274321/33457248-83ec1a6a-d5e7-11e7-8e06-76a82d7a2215.png)

2) This is more of a bookmark with a dropdown to navigate between other pages in that level.
![image](https://user-images.githubusercontent.com/24274321/33457273-9c0fbb24-d5e7-11e7-9c93-bcbbd526d388.png)

Another suggestion would be to simply change the arrow icon to make it take up less space by removing the horizontal line coming from the middle of it and adding more space or line dividing the page title and the arrow.

@gcho1023 - I believe you are not a big fan of the back button inside the page. I think that works well when all pages are available in the left nav and the use case is always navigating hierarchically but if pages are hidden from the nav (like they are in the Fun UI Lib Website or the back button is meant to be historical), that doesn't cover those use cases.  We do have the browser button to go back historically - so maybe another option would be to just cover hierarchical backs and add it in the left nav like it is in Builder. I am removing the assignment from me but will leave it on Jose to manage next steps for this.

**Comment by LeoT7508** [comment]
@jeannewalters 

From my understanding the back button was a step backward historically. @jose ?

At one point we had a vertical rule between the arrow and the title, but that was done away with. No big deal from my end to add if its an improvement.

**Comment by saadmhybris** [comment]
Back button in builder took you back hierarchically. meaning if you are in an object detail view, clicking back would take to you the object list view. 

another comment i got from a PO regarding the back button is that they expected the back button to take you to the page with the title. for example, if you see this below 

<- product detail

they thought clicking the back button would take them to product detail page, even though they were on the product detail page already. 

maybe we don't need a back button at all unless you are in a multi setup wizard where you need to go back and forward in the process? I feel the browser back button works just fine in an angular application.

**Comment by joseegm** [comment]
The Back button was supposed to bring you back hierarchically.

So if I get it correctly people are confused that the back button is related to the title, right?

Made a quick experiment and we can have something like 

![screen shot 2017-12-04 at 10 46 04](https://user-images.githubusercontent.com/22662903/33546247-d3030806-d8e0-11e7-9935-63fa1bc738a5.png)

@gcho1023 
This will solve the issue?

**Comment by LeoT7508** [comment]
@gcho1023 

?

We already have this from a design side, an icon with a label below.

**Comment by LeoT7508** [comment]
@joseegm @gcho1023 

Zeplin Link:
https://zpl.io/aRmdmLe

![techne_2 0_action bar](https://user-images.githubusercontent.com/28761982/34735832-6f300d16-f536-11e7-97eb-aef75b862920.png)

**Comment by joseegm** [comment]
Nice!

I like the line dividing the back button and the title. That will make clear that they don't belong together now. Also the button as standard action bar button is more consistent now
