### ISSUE TITLE
Add The Grid

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#613]
Add the Grid elements to the XD file along with some visual examples

![image](https://cloud.githubusercontent.com/assets/22662903/24524996/f7eb5dbe-1598-11e7-8588-12dd86b34976.png)

![image](https://cloud.githubusercontent.com/assets/22662903/24525049/305dd9ba-1599-11e7-9e83-a90e40a512ee.png)

![image](https://cloud.githubusercontent.com/assets/22662903/24525072/43f5f5de-1599-11e7-8f97-0347e5c61c57.png)

**Comment by xak** [comment]
## Grid column specs
This is a good start. No problem with the gutter value. Since layout and grid is so closely tied to the responsive behavior, it would be nice to cement those specs as well. 

For example, Bootstrap's responsive behavior uses a "snap" grid where containers stay at a fixed certain width until a breakpoint is reached at which point it "snaps" down to a different fixed size. 
http://getbootstrap.com/css/#grid-options

They offer a "fluid" option (where content goes full width). That is the primary layout for Builder modules but we had discussed NOT liking that behavior where tables stretch out. I'm guessing we want to offer both options.

**QUESTIONS**
- Is this first illustration meant to show gutter width only or are we looking at a simplified 4-col grid only with prescriptive responsive behaviors? 
- The breakpoints shown skip some sizes, e.g., what happens from 1025-1223 and 481-767?

## Spacing specs
Looking at the last illustration. I see that we are defining 10px, 25px, 50px, and 100px spacing options.

**QUESTIONS**
- Is the "compact" option an alternative to 25px or at small screens should the default 25px reduce to 25px always with the 100px container padding going to 50px?

Thanks.
