### ISSUE TITLE
Add Typography elements

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#614]
Visuals: Leo, Dieter

![image](https://cloud.githubusercontent.com/assets/22662903/24525179/aee2eb54-1599-11e7-9cea-8a910e7be283.png)

![image](https://cloud.githubusercontent.com/assets/22662903/24525192/b9a85542-1599-11e7-8a13-9186cc2954ea.png)

![image](https://cloud.githubusercontent.com/assets/22662903/24525209/c4dc4612-1599-11e7-9aa4-883507a96dc7.png)

**Comment by xak** [comment]
## Font families
The specs are fine, it's easy to add different weights later if necessary. 

**NEEDS**
- [ ] A monospace font family for code display (low-priority)

## Font size hierarchy
This is a good start. It would be helpful to see a full spec including small text and a jumbo option for hero or empty page messaging.

**QUESTIONS**
- Is larger size type always "Dosis", otherwise it's always "Open Sans" or should there be the possibility to use all font sizes with either font?

**NEEDS**
- [ ] Each size should be defined in pixels not points.
- [ ] Each should include a line-height as a percentage of the size, e.g., 15px with line-height of 20px would be 1.33333333. This determines how text will wrap.
- [ ] Each should include a default bottom margin specification to determine how far a headline, for example, sits above a paragraph. This can be a pixel value or a percentage (coded as an `em`, e.g., 40px header with 20px bottom margin would be `bottom-margin: 0.5em`)

## Line spacing
I'm not sure what this last spec means. Is it `line-height = font-size + (font-size/3)`? This spec will not be necessary if the above section is completed. 

Thanks.
