### ISSUE TITLE
Create new Bamboo deployment 

### ISSUE THREAD

**Issue by xak** [SAP/techne#617]
Right now we can simply deploy all pushes to `v2.0` and serve the `www` directory.
There is currently no deployment task, but I'll work on that. Ideally, we can set up the Bamboo deployment and then modify it later.

**Comment by joseegm** [comment]
### Current situation
Two staging environments:

* https://techne-dev.stage.yaas.io/
  Build: https://github.com/sap/techne/tree/develop
  Status: Build and deployment is broken now

* https://techne.stage.yaas.io/
   Build: https://github.com/SAP/techne/tree/master
   Status: Working, but the website and the library are build manually and then pushed to the branch

### Pain points
1. It seems like a complicated deployment, even for a static website, since it not always working and doesn't build automatically
2. Bamboo jobs/worker are shared and are sometimes slow, sometimes shortly down

**Comment by xak** [comment]
@saadmhybris `v2.0` branch now has a gulp task to build the website. 

Run `gulp docs-build --production` and everything (CSS included) will be output to `www`. Any deployment can serve the contents of that directory.

Right now, there's not much to do except `npm install` and then the above command. That should do it. No bower deps yet. Also see README.md.

Let me know if anything needs clarification.

**Comment by saadmhybris** [comment]
created a ticket for wookies here - https://jira.hybris.com/browse/WOO-9413

**Comment by xak** [comment]
I pinged the Lukaszes on this in JIRA.

**Comment by xak** [comment]
This is being worked on. The plan is to use Github pages instead of Hybris infrastructure for the 2.0 site. This will be backed with Travis to manage the build and pushes to the pages repo. Travis will enable us to institute rules for commits, have badges for dependencies, etc. 

So the Techne documentation will live at http://sap.github.io/techne/. The README is set as the main page now with the site behind the `www` directory — http://sap.github.io/techne/www/. I will put an IN DEVELOPMENT warning at the top of the README directing users to 1.5. 

I recommend keeping this issue open until Travis is active, even though we are not blocked from deployment ... we can push the site manually for now.

**Comment by joseegm** [comment]
Finally! Great!

It is there a deployment process documented -or a task- other than `gulp docs-build --production` somewhere?

Are we using our own instance of travis? Or something like Circle CI?

**Comment by xak** [comment]
See JIRA for additional details.
https://jira.hybris.com/browse/WOO-9413

**Comment by joseegm** [comment]
Then this one can be closed. 
Automation can be treated in a different issue, since it requires some config for Travis.
