### ISSUE TITLE
Docs: Determine component taxonomy

### ISSUE THREAD

**Issue by xak** [SAP/techne#653]
Instead of listing all components in a huge list, we should consider logical groupings. The labels are work in progress. Would like some feedback.

- Structure (layout, templates)
- Collections (tables, cards, trees)
- Inputs (multi-tab editor, forms, buttons)
- Flows (wizard, tours, toolbar)
- Navigation (tabs, action bar, pagination) 
- Conveyances (tooltip, loading, icons, alert)

The idea is organize around use, i.e., if a dev needs to display collection data there are several options in Collections. We would provide recommendations about which component is best for different data sets, e.g., Product Thumbnails work best for, er, products. This approach could serve to educate about our recommended usage as much as providing the code and documentation.

I'd expect that we'd still provide an alphabetical list as well.

Something like this listing for the sidebar of the Documentation landing page ...

![Documentation landing page sidebar](https://cloud.githubusercontent.com/assets/424119/25500902/5fc931fe-2b56-11e7-89ad-6a9a379c3c4f.png)

Note: Customization above would be about theming capabilities and overriding variables. Advanced would cover topics like using only parts of the library or individual components, like EC or React respectively.

**Comment by xak** [comment]
Here's a possible wireframe for the Documentation landing page ... using the collection components. This is all very rough ...

![landingpage--l](https://cloud.githubusercontent.com/assets/424119/25501782/87c76754-2b59-11e7-99df-ef2371dfed16.png)

**Comment by joseegm** [comment]
1. **Structure**: Grid, Layouts, Frames, Spacing
2. **Collections**: List, Table, Card, Tree
3. **Forms**: Inputs, Textareas, Buttons, Radio buttons, Checkboxes, Dropdown, Multi-tab editor
4. **Navigation**: Tabs, ActionBar, ToolBar, Pagination
5. **Conveyances**: Tooltip, Loading, Icons, Alert, Tours, Wizards

Removed **Flows**, it conflicts with the definition of [Effective User Flow](https://github.com/SAP/techne/wiki/Glossary#effective-user-flow). Former **Flows** elements are now on 4 and 5

**Comment by xak** [comment]
We could use a different label from **Flows** but they are different from **Conveyances**. A gallery would also be part of **Flows** for example. If we want to combine them we just need to find a better term to describe the grouping. Any recommendations?

**Comment by joseegm** [comment]
The contents of flow were:
**wizard**: that's a series of sequential steps
**tours**: overlays signalling elements on screen
**toolbar**: which is filtering and pagination mainly

TopBar is on 4, because the component helps to navigate the data on screen shown.

wizards and tours are overlays on the screen that's why they are on 5.

a gallery fits on 2, is a set of elements in this case: pictures, photos. -added to 2 on https://github.com/SAP/techne/issues/653#issuecomment-297940173

We put those elements into more fitting categories, then we don't need the former **Flows**. Categories. Unless... we want to split Navigation and filtering, but in that case the ToolBar will be a mixed component, invalidating the whole categories.

**Comment by joseegm** [comment]
@xak So, is https://github.com/SAP/techne/issues/653#issuecomment-297940173 the final list?

**Comment by xak** [comment]
If it's my call, then sure, works for me.

**Comment by joseegm** [comment]
All right this will be used as starting point to organize the components for #652
