### ISSUE TITLE
Change classes naming scheme to a more type-friendly one

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#661]
issue goal: change the css classes naming scheme to other more easy and faster to type.

Names like
```css
.tn-primary-nav__directory 
```
are hard to type and remember. Mixing ` - ` and `_ ` is difficult to remember and type. Even more accentuated when using `__ `.

Sample of this 
https://github.com/SAP/techne/blob/v2.0/dist/css/techne-all.css#L185
and following style declarations.

###  Solution
Use a simple naming scheme with only one separator. Avoid double separators.
```css
.tn-primary-nav-directory
``` 

**Side note**: using the present notation is not useful to take advantage of frameworks like Angular; that converts camelCase to dash-case and viceversa.

**Comment by xak** [comment]
This is correct BEM notation. The `primary-nav` is the block, `directory` is the element. 
See https://css-tricks.com/bem-101/

Using dashes is standard for CSS notation just like Bootstrap. Can you show me how this is problematic for Angular? Techne now uses this notation, have there been issues with it?

**Comment by joseegm** [comment]
Angular directive query default from dash-case to cameCase
https://plnkr.co/edit/kdpvLUfn8coRtJAOaWUK?p=preview

It is hard to read, hard to type and remember classes like `one-two--three__four` and also error prone as `one-two-three-four` won't work. The fact that we are using it on v1.5.x doesn't mean it is the right approach. The naming scheme can be improved.

**Comment by xak** [comment]
I don't understand what the example is showing. Where is dash-case being transformed to camelCase? I also don't know what your recommendation is. Do you suggest we use TitleCase for class names? That case has generally been reserved for JavaScript. When looking at markup it is therefore easy to see what I JS and what is CSS.

As I said before, it is a standard, well-recognized convention to use dash-case for CSS names. Please find an example of an implementation by one of our teams where this will not work or causes major problems. Based on my research, many, many teams are using this notation and I have heard no one express this as an issue.

**Comment by joseegm** [comment]
As per issue goal and proposed solution on https://github.com/SAP/techne/issues/661#issue-226579060

The problem this issue is addressing is removing the ` -- ` and ` __ `. That's already stated in the **Solution** at https://github.com/SAP/techne/issues/661#issue-226579060

**Comment by xak** [comment]
That solution is insufficient. BEM clearly separates the parts of a component into the root (block) from it's children (element) and then logically show differences (modifier). This maps perfectly to components. 

The double underscores and dashes are intentional and serve an important function esp. when there are multiple descriptors used in each part like `.foo-bar__baz-foo--bar-baz`. This is much easier to understand than `.foo-bar-baz-foo-bar-baz`.

The old way of doing things was to use dashes as you describe and it led to all kinds of problems of understanding. BEM solves those problems even though it is more verbose. But I have yet to find a developer who couldn't see the usefulness of that separation even if they don't like the syntax.

Dashes alone will not work. Perhaps a TitleCase approach `FooBar-BazFoo-BarBaz`could be used but I think that would be more confusing since it's a custom solution and not seen widely. I've researched this extensively and BEM is the best that I've seen when building design systems.

**Comment by joseegm** [comment]
`.foo-bar__baz-foo--bar-ba` translated to  BEM  will be `.block-element__modifier-block--element-element`or I have a different definition of BEM -Block Element Modifier?
Such a example is agains BEM nesting principle https://en.bem.info/methodology/quick-start/#nesting-1

The modern approach, is the main libraries out there are doing it: No presence of ` -- ` or `__ ` Please look at the code:

* Bootstrap - https://v4-alpha.getbootstrap.com/components/card/#kitchen-sink
* Material - https://plnkr.co/edit/sah8avmpYRZcbCftsNgy?p=preview
* Blueprint - http://blueprintjs.com/docs/#core/components/card.interactive-cards

200% sure those teams did their homework and decided not to use ` -- ` and ` __ `. For very good reasons. As stated before: hard to type, hard to read and error prone.  
Nobody building modern CSS is doing it.

It is fine if we want to have `.block-element-modifier` but absolutely not `.block--element__modifier`.

**Comment by saadmhybris** [comment]
-- or __ makes it easy to understand the class structure whereas a single - will not reflect the BEM methodology. 

For example - side-nav--search-box--small vs - side-nav-search-box-small 

With the --, you can clearly see where the blocks end and element or modifier begins.

The class names will get lengthy but it will definitely be a win in the long run as we don't have to deal with nested classes and reduce CSS specificity.

I personally, don't like __ so maybe we can agree to just using -- for blocks and modifiers.

**Comment by xak** [comment]
@joseegm `.foo-bar__baz-foo--bar-baz` is showing the problem when you have compound names for each of those, like `primary-nav__list-item--getting-started` with dashes that would be `primary-nav-list-item-getting-started`.

As I said before, I will bring this up tomorrow with the UI devs and get their input.

**Comment by joseegm** [comment]
Don't see a problem with `.side-nav-search-box-small` or `.primary-nav-list-item-getting-started`. 

Since the problem we are trying to solve is readability.... 

Why not this usage
```html
<nav class="tn-primary-nav">
    <ul>
        <li class="tn-list-item tn-getting-started"> ... </li>
        <li class="tn-list-item"> ... </li>
    </ul>
</nav>
```
Which is even shorter, and definitively `tn-list-item tn-getting-started`is more readable than `tn-primary-nav-__ist-item--getting-started`

**Comment by xak** [comment]
I find those long class names confusing and I like BEM because it brings some logic to class name structures. As I said, it's perfectly suited for components where you have a root block and multiple elements and states. 

Your example here is simpler but it does not carry the block name throughout and is confusing as it seems that `tn-list-item` and `tn-getting-started` are blocks and I would then expect to see a stylesheet for each of those. This compounds when you actually have components inside components and it's not clear what is the root and what is an element and what is a modifier.

BEM is not perfect. To your side question, for example, I don't like that duplication of class names. In my own non-SAP work I use my own interpretation — https://github.com/thestrongelement/strong-css/blob/master/BEM.md — but this is not practical for our purposes so I'm not recommending it. Using the attribute selector `[class=^=tn-primary-nav__list-item--]` was my attempt to solve that. We can still solve it but we must make sure we architect the CSS to account for that. I have done this and will make sure there is a component SASS template that explains how to approach the coding.

So I do understand your points about readability and simplicity, but a good architecture is about more than that. It must weigh those things with a lot of other concerns. I also understand that for the types of shallow components we are creating, BEM may be overkill. I chose BEM only because it has worked well for me and I've seem examples in our code base (Techne and elsewhere) so I assumed there would be a small learning curve.

I will discuss this with Saad and other UI devs and we will devise a final recommendation.

**Comment by joseegm** [comment]
All right. Let's do this: use BEM when it makes sense with only one ` - `to simplify things -no need to think when it is double or simple dash- and stay with the zeitgeist.

**Important**: When using BEM avoid at all cost the problem on #659
