### ISSUE TITLE
Implement Cards Component

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#692]
Design Specs on #678

**Comment by joseegm** [comment]
@xak Just saw the specs on the wiki now https://github.com/SAP/techne/wiki/Component-Specs:-Collections#cards

We can merge that with my first draft from https://github.com/SAP/techne/issues/678#issuecomment-304221561 like this:

* keep the *media* identifier for the images, that's a better name than image, more abstract.
* `body` -> `content` more general and widely used.
* `top`-> `vertical` keep is flexible if we want to put the media at the bottom we can use the same modifier class.
* `is-disabled` -> `disabled` "is" seem redundant since the modifier is added to the element like `.tn-card .tn-disabled`.
* `full-width` is the same as the current `stacked`

**Comment by xak** [comment]
Thanks or the feedback ...

* Changed to the element from image to media but added a `--padded` modifier for icons that would not be full bleed like an image.
* Change to content
* Changed top to vertical
* Using `is` and `has` prefixes differentiates these classes as states. It helps devs understand that **THESE** are the only classes that should be changed with JavaScript. This is how we contract with the backend for interactivity. For our part, these classes would **NEVER** be styled globally, they **MUST** be directly attached to a block or element class, meaning we would **NEVER** do `.tn-disabled { color: lightgray; }` globally, only `.tn-card.is-disabled { color: lightgray; }`°. The latter example better expresses the state relationship. Using `disabled` or `active` alone could be confused as a component and feels like it should have independent styling divorced from the component it acts upon. I have noted native/ARIA attributes like `[disabled]`/`[aria-selected]` if applicable and we should encourage that usage when appropriate, yet we'll provide fallback classes as well.°° 
* Added `&--stacked` as an option but I'd like to establish a common modifier vocabulary as much as possible. `full-width` is more generic and could apply to tables, lists, etc. where `stacked` may not be as flexible. 

Wiki has been updated. We can consider header and footer elements based on all of Denise's uploads.

° I'd prefer not to namespace these for ease of use. Since they are not global rules these is no concern about unintended cascade effects. It's possible that another library could interfere with our styles, but even then, our specificity would override any global rules established in that library. I see the value of name spacing, of course, but I wanted to argue my case.
°° The idea is that these are helpers for [standard widget states](https://www.w3.org/TR/wai-aria/states_and_properties#attrs_widgets) — `.is-checked`, `.is-hidden`,`.is-selected`, `.is-readonly`, `.is-required` — and the preference is to use the attributes (and not out classes). However, I believe A11Y in Angular requires a plugin and most devs are using `ng-class` and not using ARIA attributes.

**Comment by joseegm** [comment]
We still need to support the devs that use the markup with attributes:
```css
input.tn-is-disabled, input[disabled] {}
```

`full-width` it is, works for more components down the line indeed.

A [quick search on github](https://github.com/search?l=CSS&q=%22.is-disabled%22&type=Code&utf8=%E2%9C%93) reveals, lots of libraries and jquery pluggins using `.is-disabled` with CSS and JS. Since we cannot prevent people mixing libs and pluggins etc: It is easier when a problem arise to see where the class comes from if it is all under the same name space.

**Comment by joseegm** [comment]
@xak @saadmhybris @like-me1 
To drastically reduce the scope of this in context of the milestone
https://github.com/SAP/techne/milestone/10

We gonna only implement
1. Common Cards
2. Card with supporting images: **Only the ones with images on the left** not the other ones.
from https://github.com/SAP/techne/issues/678#issuecomment-303422400

Should we keep this issue for the whole cards and spawn a new one only for that in context of the milestone?

**Comment by joseegm** [comment]
@xak 
Why this issue was not used for the implementation? It contains valuable information on it. 

Instead other issue was open... https://github.com/SAP/techne/issues/709 that was is missing the decisions made on https://github.com/SAP/techne/issues/692#issuecomment-304336537

**Comment by xak** [comment]
Everything relevant was captured in #709 with additional information. This can be closed now.
