### ISSUE TITLE
techné vs. techne

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/techne#703]
There are places where techné is not used with the stressed 'é'. this is very minor one

**Comment by joseegm** [comment]
We are leaving out the `é` too much hassle to type and everybody pronounce it as they like anyway.

**Comment by joseegm** [comment]
@SAPMontreal 
Guess https://github.com/SAP/techne/issues/703#issuecomment-306422964 answered the issue. 
I'm closing it.

If there is something more related to the `é` in Techne you can reopen.

**Comment by xak** [comment]
@joseegm I think Deno's point was that it _should_ be changed across the site to be consistent. This is related to the current site, not necessarily a new version. I have also seen instances on yaas.io where it is lowercased.

If you don't want to change it then you can close it, otherwise this can go in the backlog where it could be picked up. It would be a quick search and replace to fix in our codebase.
