### ISSUE TITLE
Docs: Implement color specs

### ISSUE THREAD

**Issue by xak** [SAP/techne#728]
Build out a page for the color palette. 

Update function based on new color specs.
https://sapse.invisionapp.com/d/main#/console/11153756/239338947/preview

Show usage of helper classes, examples ...
- `has-color-COLOR_NAME`
- `has-background-color-COLOR_NAME `

**Comment by joseegm** [comment]
@xak 
Can you post the last version of the Colors here? Remember that the github repo is the main source of information. Invision is okay if you need it but is not the focus. Thx.

Don't forget to attach the PR for this.

**Comment by joseegm** [comment]
@xak 
The Final PR is still missing here.

**Comment by xak** [comment]
The PR was #788 and has been merged.

**Comment by joseegm** [comment]
There is still a problem with the name "inverse" originally posted at: https://github.com/SAP/techne/issues/765#issuecomment-314693015

posting it again here for context:

**The name "inverse" doesn't reflect the usage. I'll include those colors inside of "Text" as well. Since they will be light colors, so they don't get confused by "Neutral"**

We need a more descriptive name.
