### ISSUE TITLE
Improve component documentation structure

### ISSUE THREAD

**Issue by xak** [SAP/techne#786]
As a developer, I would like to see more clearly the "API" for each component particularly how modifiers and state classes are applied. It will be easier to write logic for components if this information is clearly presented.

See http://sap.github.io/techne/www/components/cards.html where the raw information is shown. At the top you'll see the basic structure with the block, elements, modifiers and states defined. The `?` means optional. This is probably not the best way to note this information but it could be shown in a table.

```
.tn-card+(--button,--vertical)+(.is-disabled|[aria-disabled=true])
    .tn-card__media+(--round,--fill)?
    .tn-card__content
        .tn-card__header?
        .tn-card__description?
        .tn-card__status?
    .tn-card__actions?
```

The example on the page below attempt to show how modifiers can be added to change the component. By exposing this information a developer will not have to compare sample code to determine how logic should be implement. For example, if mixing cards with image and those without, the developer only needs to include the `tn-card__media` element along with an image path. That is the only difference between those two cards.

Additionally, each component block will need to support description copy and block for notes. 

## NOTE: This story is for a user experience expert to assess the component structure and present a wireframe with the best way to organize this information as an improvement over the 1.5 documentation.

**Comment by joseegm** [comment]
@xak 
**From the abstract description you provided.**

A UX solution was designed and implemented to exemplify the functionality. This will be used for user testing to validate the need for such a feature. 

Please look at the attached video to see the functionality in action
[component-structure.mov.zip](https://github.com/SAP/techne/files/1165567/component-structure.mov.zip)

**And the implemented solution at**:
https://techne-alpha.firebaseapp.com/components/containers/card

**Comment by xak** [comment]
Thanks for putting this together but the interactivity doesn't add anything. A table would be just as informative.

Perhaps this is more of a content exercise than UX. Looking at the following examples, they do a good job of explaining the concepts but also exposing the tech and how the block build on top of each other.

https://material.io/components/web/catalog/cards/
http://carbondesignsystem.com/components/card/code
https://www.lightningdesignsystem.com/components/cards/

In our presentation, everything is presented linearly with equal weight. For example, a card with a round image is a minor modification of the media element — ` .tn-card__media+(--round,--fill)?` but we present it equally as the disabled card which is a state of the base element — `tn-card[aria-disabled=true]`. Knowing now that we have distinct blocks and elements with properties and states, we could do a better job of organizing the components to educate users about the structure. Maybe a table under the media card that lists all the options for the `tn-card__media` element. If we simply show an example and expect devs to copy the code, we're not doing anything to educate them about the library and the design system. 

**However, we can defer this for now.** It's more important to get the basics in before we start looking at improvements. We can view this as an enhancements later. Just leave this in the backlog and we can revisit somewhere down the line.

**Comment by joseegm** [comment]
The table doesn't represent the class/elements hierarchy. So this representation is more informative.

The interactivity let you focus on one element at the time and jump to the corresponding example.

The type of modifier is displayed as "tags" on every element. Shown bellow:
![screen shot 2017-07-24 at 09 28 02](https://user-images.githubusercontent.com/22662903/28512589-d77f7e88-7052-11e7-993b-73708ae33096.png)

**It is confusing: you want to defer this to later since for you was really important even for putting other ticked blocked. https://github.com/SAP/techne/issues/822#issuecomment-315385952**

This can be finished now, instead of leaving it on the backlog.

**Comment by xak** [comment]
This is not a holistic solution, it's an add-on at the bottom of the page with no context. 

It's not worth pursuing at this time esp. since we have little in the way of website strategy and use cases. We can revisit it later, perhaps dedicate a resource to investigate the content strategy and IA of the site.

It's more important right now to get stuff on a page and we can better organize later on. That's the best way to move forward. _I removed my comment about this being a blocker because I thought better of it. You decided to put it back._

**Comment by joseegm** [comment]
### It is a holistic solution by definition:
1. **All parts** are interconnected: the structure represents different types or status of a given component. 
2. **The whole** result of the visual representation contains: all options, modifiers, parameters and classes that can be used; linking to the corresponding example.

This is a solution we can use now that solves problems like:
1. Illustrate the structure of the component. **That was what this issue is all about.**
2. See all classes, options, modifiers, parameters that can be used and see the example right away.
3. Serve as a index for the component page.

We are dealing here with the Component page in particular, only. Please keep the right context.

**Comment by joseegm** [comment]
@xak 
We talked about this to be used as an index for the component page. But is centered on the developer personal so it doesn't work as the main index.

Still it is a good idea so I'll include it in the design of the Component page at #842

**Comment by xak** [comment]
@joseegm This is not important for an MVP. I don't recommend spending any more time on it.

**Comment by joseegm** [comment]
@xak 
**What's the MVP you mentioned?**

Since you open this issues your lack of interest now is surprising.
