### ISSUE TITLE
Docs: Update Cards based on new color specs

### ISSUE THREAD

**Issue by xak** [SAP/techne#798]
Circle back to update the cards to reflect the new colors. Some colors are missing now.

**Comment by joseegm** [comment]
@xak 
Where is the PR for this?

**Comment by xak** [comment]
@joseegm If you look at the timeline above, the commits and the PR are all clearly reflected. It done, it's merged, it's fine, there's no problem here.

Saad found a bug during the code review and requested changes. The second commit was to fix that. Are you suggesting we merge the defect and then create a new issue and a new PR to fix the defect?

**Comment by joseegm** [comment]
@xak 
No. I'm not suggesting that. What you described is exactly how it looks from the timeline. 

It is also a bit confusing since other code different from what's been done in this  issue has been committed to the same branch
https://github.com/SAP/techne/commit/8e56ccd4d061b5ecf762d1cf8353786d6cadf939#diff-763f975ef2d4cae80ac6e89925f32ed4L19
Since that's pretty prominent on the commit page and not noted on https://github.com/SAP/techne/pull/799#issuecomment-314595833
I though it was something else been merged after.

**Comment by LeoT7508** [comment]
@xak 

The only issue I see with the cards is we need to add the interactions for the more "..." icon, and the "Generate Access Token" text button.

**Comment by xak** [comment]
@LeoT7508 We need to circle back on those. The "More" is a contextual menu which hasn't been built and uses icons which are not done yet. I can add an actual button for "Generate Access Token" however. I'll put it on my list.

**Comment by LeoT7508** [comment]
@xak 

We can talk more about the contextual menu and the Generate Access Token later. The rest of this looks spot on.
