### ISSUE TITLE
Design Lists

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#806]
goal: Design a more useful version of the list 

### Current v1.5.x
<img width="667" alt="screen shot 2017-07-13 at 12 24 02" src="https://user-images.githubusercontent.com/22662903/28162083-2fc2ca90-67c6-11e7-8f71-71d82133cfa2.png">

### Tasks
- [x] Identify Uses cases
- [x] Define UX elements
- [x] Visual Design
- [x] Document results

**Comment by xak** [comment]
- See current [YasS list-group examples](https://sapse.invisionapp.com/d/main#/projects/boards/5484242)
- Since this is an [enhancement of a Bootstrap component](http://getbootstrap.com/components/#list-group), additional Bootstrap modifications may need to be accounted for. See 
- See [schema](http://jeremydorn.com/json-editor/?schema=N4IgJAzgxgFgpgWwIYgFwhgF0wB1QenwCsIB7AOwFpp5kA6UgJwHN8ATRpAM00oAYALPhqIkAYhAAaEEjZsAlpnkUkAGwAKjUjjiMlcCGi5qIcaWzhd55RcvKHUwAL7T5bNBmx5CcAB5IEHFU4OihSBHw/AKCQkgopECVMYI9MKlV5CF5mLQBXHAScLR09eQM0UEVEB1BZBSUVVQBJTGq0TEZcsxA3D3wi7V19CHwqhENXVvGKmTlbRs1B0vLUY1VTV3d0fuKhspGxg6mJkAGS4ZnW30wZ3u2zvYNR4+fqnaXh/Cub6UwATx0HiyjGszBAThcIEYcAAjrl5NCtgBtRJ+G4AXV+ALgHlIACMiHAoDdIQhrC02qgAIxYwHoJCMTh/BK5GxwuAU6aoDpdCHSaFwhFwZE9Y4gTGJbG4glEklAA==&value=N4IglgLgpgtgziAXAbVNAHhJIQF8C6uQAAA=&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction) for the single use case in the 1.5 library

**Comment by joseegm** [comment]
@xak 

The List component will become more complex with icons, actions, check boxes. As we decided to scrap the grouped cards in favor of the lists on https://github.com/SAP/techne/issues/679

1. Thanks for the examples
2. We are not basing it on bootstrap for 2.0
3. How is the schema helpful for the design at this point?
4. BEM structure is for 1.5, this Component is different in 2.0. 
    So, I guess that have to be redefined.

**Comment by xak** [comment]
The schema is basic since it's only a list that can have one or more items. The schema (and thus the data object) should be updated as new requirements are identified. I'm not sure how the component different in 2.0, but as with the schema, once new requirements are identified the classing will be adjusted.

Please consider during UX and design how a component would be represented as data and what is required (e.g., the properties and states) to initialize the component.

**Comment by joseegm** [comment]
How the list will look like will be defined in this issue.

I need more clarification:
1. Who is in charge of defining the schema?
2. Is the schema based on the design?
3. Who is in charge of updating the schema once a design change is made?
4. What you mean by "initialise the component"?

**Comment by xak** [comment]
Thanks for asking, this goes to the heart of how we can create a strong through-line from reqs to implementation.

1. The tech team should be ultimately responsible for the schema. Think of it like an API and UI being designed simultaneously from the same requirements document. If requirements change, both could be impacted.

2. Not necessarily. It's more about an agreement on the data. If you're building a biography card for employees, you'd need something like for each `bioItem` ...

```
{
  "name": "Saad Mohiuddin",
  "email": "saad.mohiuddin@sap.com",
  "pic": "images/saad.png"
}
```

With that, the dev could start building a DB and create an API to retrieve the employee data. The designer could build a UI to display that data. If the design wants to display `Mohiuddin, Saad` that affects the data — you'd need `"firstname": "Saad", "lastname": "Mohiuddin" — so that would need to be communicated. Maybe the dev team comes back and says they don't have pictures for everyone, so the design needs to create a placeholder image when `bioItem.pic` is `null`. There also needs to be a design for when `items.length == 0`.

This isn't about limiting options for design but about understanding the implementation and optimizing delivery. I believe, whole-heartedly, that this benefits every member of the team. It establishes that important shared understanding and builds a common vocabulary.

3.  It would be the dev team who owns the component "API". The communication/collaboration is described above. There are [tools](https://jsonschema.net/#/editor) to aid the effort. 

4. I mean the component constructor, the data needed by the component ...
```
<ul>
   <li *ngFor="let item of items">{{item.text}}</li>
</ul>
```

I don't know exactly how this would work best in the process, but I'd like to at least be able to discuss the schema upfront or work ahead if possible. I think it will greatly help the development team and has lots of potential.

**Comment by joseegm** [comment]
To resume your answers:
1. The dev team is responsible to define the schema. Not UX.
2. The schema is not based on the design.
3. The schema is updated by the dev team after a design change is made.
4. That is an angular `ngFor` snippet. We only provide the HTML and CSS. 
    HTML+CSS elements don't need initialisation.

### Conclusion
The schema doesn't affect the design and the dev team is in charge to maintain it.

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_lists](https://user-images.githubusercontent.com/28761982/29468844-831dcc60-840b-11e7-8731-9195ddb23346.png)

**Comment by xak** [comment]
@LeoT7508 The Search input field uses a blue "x" to clear out the input field and this gray "x" is intended to delete the item altogether. 

![screen shot 2017-08-18 at 12 34 12 pm](https://user-images.githubusercontent.com/424119/29470334-9460730a-8411-11e7-88d9-d643588c4951.png)

Seeing this here, I wonder if the colors should be reversed for these with the blue used here to signify an **action** with consequences. The search input isn't quite the same type of action. The current implementations I've seen use a red "x".

But as you note, this is just an icon and will be treated like an add-on that can take any content ... so it's will be simply an icon button which could be the "x" or a trash can, or pencil, etc. For demo purposes, however, we should show the recommended implementation.

**Comment by LeoT7508** [comment]
@xak 

This was just meant to be a placeholder. We can change it to a grey, blue, or whatever is appropriate.
