### ISSUE TITLE
Docs: make the pages responsive

### ISSUE THREAD

**Issue by like-me1** [SAP/techne#832]
The main content of the pages needs to be responsive. For now, it breaks on mobile the footer and creates a horizontal scroll.

**Comment by saadmhybris** [comment]
@like-me1 - you can work on this as well. we need some rough responsive behavior so that it's at least some what usable if someone pulls up the documentation site on mobile. 

we can mimic the yaas site navigation for the time being. 

- top menu collapses into with the hamburger. let change the hamburger icon to a down arrow like we have on the old site 'super header'. https://techne.yaas.io/
- add a hamburger icon next to techne site name that will slide in and out the side nav. 

bootstrap css and js already included in the project so you can use that to do the responsive behavior.

**Comment by saadmhybris** [comment]
Closing this issue as it was related to the old structure of the site.
